services:
    web:
        image: 'nginx:1.21.3'
        container_name: 'f7_nginx'
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: 'mgv/php:8.1.1-fpm' # based on php:8.1.1-fpm-alpine3.14
        container_name: 'f7_phpfpm'
        volumes:
            - ./code:/code